// Usuarios
export const GET_USERS = 'GET_USERS';
export const GET_PROFILE = 'GET_PROFILE';
export const CAMBIAR_ESTATUS = 'CAMBIAR_ESTATUS';

// Roles
export const GET_ROLES = 'GET_ROLES';
export const CREATE_ROL = 'CREATE_ROL';
export const UPDATE_ROL = 'UPDATE_ROL';
export const DELETE_ROL = 'DELETE_ROL';

// Promociones
export const GET_PROMOCIONES = 'GET_PROMOCIONES';
export const CREATE_PROMOCION = 'CREATE_PROMOCION';
export const UPDATE_PROMOCION = 'UPDATE_PROMOCION';
export const DELETE_PROMOCION = 'DELETE_PROMOCION';
export const GET_PROMOCIONES_BY_LUGAR = 'GET_PROMOCIONES_BY_LUGAR';
export const GET_PROMOCIONES_BY_SOCIO = 'GET_PROMOCIONES_BY_SOCIO';
export const REGISTRAR_CLIC = 'REGISTRAR_CLIC';

// Auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGOUT = 'LOGOUT';

// Categorias
export const GET_CATEGORIAS = 'GET_CATEGORIAS';
export const CREATE_CATEGORIA = 'CREATE_CATEGORIA';
export const UPDATE_CATEGORIA = 'UPDATE_CATEGORIA';
export const DELETE_CATEGORIA = 'DELETE_CATEGORIA';

// Lugares
export const GET_LUGARES = 'GET_LUGARES';
export const GET_LUGAR_BY_ID = 'GET_LUGAR_BY_ID';
export const CREATE_LUGAR = 'CREATE_LUGAR';
export const UPDATE_LUGAR = 'UPDATE_LUGAR';
export const DELETE_LUGAR = 'DELETE_LUGAR';

// Actividades
export const GET_ACTIVIDADES_BY_USER = 'GET_ACTIVIDADES_BY_USER';
export const CREATE_ACTIVIDAD = 'CREATE_ACTIVIDAD';

// Notificaciones
export const GET_NOTIFICACIONES_BY_USER = 'GET_NOTIFICACIONES_BY_USER';
export const CREATE_NOTIFICACION = 'CREATE_NOTIFICACION';
export const DELETE_NOTIFICACION = 'DELETE_NOTIFICACION';

// Rutas
export const GET_RUTAS = 'GET_RUTAS';
export const CREATE_RUTA = 'CREATE_RUTA';
export const UPDATE_RUTA = 'UPDATE_RUTA';
export const DELETE_RUTA = 'DELETE_RUTA';

// Tokens
export const GET_TOKENS = 'GET_TOKENS';
export const GET_TOKENS_BY_USER = 'GET_TOKENS_BY_USER';
export const CREATE_TOKEN = 'CREATE_TOKEN';
export const DELETE_TOKEN = 'DELETE_TOKEN';

// UsoDigital
export const GET_USO_DIGITAL_BY_USER = 'GET_USO_DIGITAL_BY_USER';
export const CREATE_USO_DIGITAL = 'CREATE_USO_DIGITAL';